# Generated by Django 5.1.1 on 2024-09-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
        ('auth', '0014_remove_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
